// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/dragon2org/wireg/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wireg.go:

func injectFooBar(foo Foo) FooBar {
	bar := provideBar()
	fooBar := provideFooBar(foo, bar)
	return fooBar
}
