// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/dragon2org/wireg/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wireg.go:

func injectFoo() Foo {
	foo := _wireFooValue
	return foo
}

var (
	_wireFooValue = Foo{X: 42}
)
