// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/dragon2org/wireg/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wireg.go:

func injectedMessage(t title, lines ...string) string {
	string2 := provideMessage(lines...)
	return string2
}
