// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/dragon2org/wireg/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wireg.go:

func InitializeFooStore() FooStorer {
	foo := _wireFooValue
	store := NewFooStore(foo)
	return store
}

var (
	_wireFooValue = Foo("foo hello")
)
